#version 430 core

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

uniform float dt;
uniform int particleCount;

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if (i >= uint(particleCount))
        return;

    particles[i].position +=
        particles[i].velocity * dt;

    if (particles[i].position.x < -1.0 ||
        particles[i].position.x > 1.0)
    {
        particles[i].velocity.x *= -1.0;
    }

    if (particles[i].position.y < -1.0 ||
        particles[i].position.y > 1.0)
    {
        particles[i].velocity.y *= -1.0;
    }
}